### PR TITLE
fix: allow institutional managers to edit users from their institutions

### LINKED ISSUE #120: [Bug] Institutional Managers cannot edit users from their institution
It is no longer possible for Institutional Managers to access the `user-edit.php` page for the users belonging to their institution.

### Steps to replicate
- Log in as an Institutional Manager
- Go to Users Page. You should see all the users belonging to the institution.
- Click on `Edit` link below a user in the users list.

**Actual behaviour:** You will see the `Sorry, you are not allowed to access this page.` page.
**Expected behaviour:** You should be able to access to the user-edit page to edit the user's profile.

### PR DESCRIPTION
**Pull request by richard015ar**
This PR would fix https://github.com/pressbooks/pressbooks-multi-institution/issues/120 but @arzola is working on a [refactor](https://github.com/pressbooks/pressbooks-multi-institution/issues/76) of this class. It is just to show him where the problem is, that might help him to apply the necessary changes to his new implementation.

### CODE REVIEW

File: src/Actions/PermissionsManager.php [hunk 1]
```diff
@@ -351,8 +351,8 @@ public function handlePagesPermissions($institution, $institutionalManagers, $in
             $institutionalUsers = apply_filters('pb_institutional_users', []);
 
             if ($currentPageParam === 'pb_network_analytics_userlist' || $currentPage === 'users.php' || $currentPage === 'user-edit.php') {
-                if (isset($_GET['user_id']) && !in_array($_GET['user_id'], $institutionalUsers)) {
-                    $isAccessAllowed = false;
```
Comment (richard015ar) [inline src/Actions/PermissionsManager.php]: It is false by default for `user-edit.php` page, since it won't meet this condition https://github.com/pressbooks/pressbooks-multi-institution/pull/121/files#diff-c16b712644fb16982b2669cf48af33f13f5621263e53e518834934309434bd87L328, so we need to explicitly declare it true in this case.

Comment (arzola) [reply src/Actions/PermissionsManager.php]: I think this should be $_REQUEST instead to allow the form to be saved too

```
if (isset($_REQUEST['user_id']) && in_array($_REQUEST['user_id'], $institutionalUsers)) {
                    $isAccessAllowed = true;
                }
```

**Review by arzola — CHANGES_REQUESTED** [review]
It requires to handle also the post method to handle the save action

**Review by arzola — APPROVED** [review]
LGTM
