### PR TITLE
fix: remove special print for name column

### LINKED ISSUE #73: Styling/layout improvements
We have a series of desired layout and styling improvements we'd like to see implemented before release: https://docs.google.com/document/d/1xFp1yAdHqC2NIyF4TxMWCMjYWJJQFAqndyGY0c6I1rI/edit

## Nav Menu
- [x] place new `Institutions` option directly below `Users` for super admins & network managers. if not possible, put above `Books`
## Institutions list
- [x] default display 50 items per page
- [x] reduce size of Institution name to match other text
- [x] change ‘Unassigned’ and ‘Total Items’ to same font size & weight as Institution names
- [x] reduce width of books/users columns (extra space spread across remaining columns)
- [x] improve contrast between text & background color and add clearer separator between calculated rows at bottom (‘unassigned’ + ‘total items’) (#C3C4C7)
- [ ] book usage number should link to institution’s book list [skip for now]
- [ ] user usage number should link to institution’s user list [skip for now]
## Add Institutions page
- [x] make sure input fields are top aligned with prompt text
## Assign users
- [x] don’t bold user’s name
- [x] default display 50 items per page
- [x] link username to (edit) user profile 
## Assign books
- [x] default display 50 items per page
- [x] apply border bottom to all table cells
- [x] Book titles shouldn't be wrapped in `<p>` elements
- [x] book URL should link to book dashboard rather than homepage (add /wp-admin)
- [ ] reduce width of institution column to 300px (extra space can go to title / book admin) 
## Book/user list
- [x] Only display institutions in the filter if there are books/users which have that institution assigned (match behaviour of other filters)
- [x] Display `Unassigned` as the institution value in the book list when books are not assigned to any institution
- [x] Remove `institution_id` column from book list CSV downloads

### PR DESCRIPTION
**Pull request by richard015ar**
This PR fixes https://github.com/pressbooks/pressbooks-multi-institution/issues/73#issuecomment-1997825011, https://github.com/pressbooks/pressbooks-multi-institution/issues/73#issuecomment-1997878196, and https://github.com/pressbooks/pressbooks-multi-institution/issues/73#issuecomment-1997898451

For testing
1. Go to Institution > Assign Users and make sure the name column is printed as expected.
2. Visit the institution list and check that the buy-in column has been reduced to 65px and check the contrast of the text color on the background for the summary rows at the bottom. Background color should now be #dedede and text color should be #333.
3. Open the add/edit institution form page and note changes to link and asterisk instructions, increased width, and adjust margin for IM input field
Screenshot from 2024-03-14 10-35-25 (1)

### CODE REVIEW

File: src/Views/AssignUsersTable.php [hunk 1]
```diff
@@ -24,11 +24,6 @@ public function column_default($item, $column_name): string
         return $item[$column_name] ?? '';
     }
 
-    public function column_name(array $item): string
```
Comment (richard015ar) [inline src/Views/AssignUsersTable.php:27]: any special printing is needed for the name column, for now, it was intended with the objective to print first_name + last_name here, but it was performed in another part of this same class

**Review by arzola — APPROVED** [review]
LGTM
